DROP TABLE IF EXISTS `auto_chat_text`;
CREATE TABLE `auto_chat_text` (
  `groupId` INT NOT NULL default '0',
  `chatText` VARCHAR(255) NOT NULL default '',
  PRIMARY KEY  (`groupId`,`chatText`)
) ENGINE=InnoDB;

INSERT INTO `auto_chat_text` VALUES 
(1,'%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!'),
(1,'%player_cabal_loser%! You bring an ill wind!'),
(1,'%player_cabal_loser%! You might as well give up!'),
(1,'A curse upon you!'),
(1,'All is lost! Prepare to meet the goddess of death!'),
(1,'All is lost! The prophecy of destruction has been fulfilled!'),
(1,'The prophecy of doom has awoken!'),
(1,'This world will soon be annihilated!'),
(2,'%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!'),
(2,'%player_cabal_loser%! You bring an ill wind!'),
(2,'%player_cabal_loser%! You might as well give up!'),
(2,'A curse upon you!'),
(2,'All is lost! Prepare to meet the goddess of death!'),
(2,'All is lost! The prophecy of destruction has been fulfilled!'),
(2,'The prophecy of doom has awoken!'),
(2,'This world will soon be annihilated!'),
(3,'%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!'),
(3,'%player_cabal_loser%! You bring an ill wind!'),
(3,'%player_cabal_loser%! You might as well give up!'),
(3,'A curse upon you!'),
(3,'All is lost! Prepare to meet the goddess of death!'),
(3,'All is lost! The prophecy of destruction has been fulfilled!'),
(3,'The prophecy of doom has awoken!'),
(3,'This world will soon be annihilated!'),
(4,'%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!'),
(4,'%player_cabal_loser%! You bring an ill wind!'),
(4,'%player_cabal_loser%! You might as well give up!'),
(4,'A curse upon you!'),
(4,'All is lost! Prepare to meet the goddess of death!'),
(4,'All is lost! The prophecy of destruction has been fulfilled!'),
(4,'The prophecy of doom has awoken!'),
(4,'This world will soon be annihilated!'),
(5,'%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!'),
(5,'%player_cabal_loser%! You bring an ill wind!'),
(5,'%player_cabal_loser%! You might as well give up!'),
(5,'A curse upon you!'),
(5,'All is lost! Prepare to meet the goddess of death!'),
(5,'All is lost! The prophecy of destruction has been fulfilled!'),
(5,'The prophecy of doom has awoken!'),
(5,'This world will soon be annihilated!'),
(6,'%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!'),
(6,'%player_cabal_loser%! You bring an ill wind!'),
(6,'%player_cabal_loser%! You might as well give up!'),
(6,'A curse upon you!'),
(6,'All is lost! Prepare to meet the goddess of death!'),
(6,'All is lost! The prophecy of destruction has been fulfilled!'),
(6,'The prophecy of doom has awoken!'),
(6,'This world will soon be annihilated!'),
(7,'%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!'),
(7,'%player_cabal_loser%! You bring an ill wind!'),
(7,'%player_cabal_loser%! You might as well give up!'),
(7,'A curse upon you!'),
(7,'All is lost! Prepare to meet the goddess of death!'),
(7,'All is lost! The prophecy of destruction has been fulfilled!'),
(7,'The prophecy of doom has awoken!'),
(7,'This world will soon be annihilated!'),
(8,'%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!'),
(8,'%player_cabal_loser%! You bring an ill wind!'),
(8,'%player_cabal_loser%! You might as well give up!'),
(8,'A curse upon you!'),
(8,'All is lost! Prepare to meet the goddess of death!'),
(8,'All is lost! The prophecy of destruction has been fulfilled!'),
(8,'The prophecy of doom has awoken!'),
(8,'This world will soon be annihilated!'),
(9,'%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!'),
(9,'%player_cabal_loser%! You bring an ill wind!'),
(9,'%player_cabal_loser%! You might as well give up!'),
(9,'A curse upon you!'),
(9,'All is lost! Prepare to meet the goddess of death!'),
(9,'All is lost! The prophecy of destruction has been fulfilled!'),
(9,'The prophecy of doom has awoken!'),
(9,'This world will soon be annihilated!'),
(10,'%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!'),
(10,'%player_cabal_loser%! You bring an ill wind!'),
(10,'%player_cabal_loser%! You might as well give up!'),
(10,'A curse upon you!'),
(10,'All is lost! Prepare to meet the goddess of death!'),
(10,'All is lost! The prophecy of destruction has been fulfilled!'),
(10,'The prophecy of doom has awoken!'),
(10,'This world will soon be annihilated!'),
(11,'%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!'),
(11,'%player_cabal_loser%! You bring an ill wind!'),
(11,'%player_cabal_loser%! You might as well give up!'),
(11,'A curse upon you!'),
(11,'All is lost! Prepare to meet the goddess of death!'),
(11,'All is lost! The prophecy of destruction has been fulfilled!'),
(11,'The prophecy of doom has awoken!'),
(11,'This world will soon be annihilated!'),
(12,'%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!'),
(12,'%player_cabal_loser%! You bring an ill wind!'),
(12,'%player_cabal_loser%! You might as well give up!'),
(12,'A curse upon you!'),
(12,'All is lost! Prepare to meet the goddess of death!'),
(12,'All is lost! The prophecy of destruction has been fulfilled!'),
(12,'The prophecy of doom has awoken!'),
(12,'This world will soon be annihilated!'),
(13,'%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!'),
(13,'%player_cabal_loser%! You bring an ill wind!'),
(13,'%player_cabal_loser%! You might as well give up!'),
(13,'A curse upon you!'),
(13,'All is lost! Prepare to meet the goddess of death!'),
(13,'All is lost! The prophecy of destruction has been fulfilled!'),
(13,'The prophecy of doom has awoken!'),
(13,'This world will soon be annihilated!'),
(14,'%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!'),
(14,'%player_cabal_loser%! You bring an ill wind!'),
(14,'%player_cabal_loser%! You might as well give up!'),
(14,'A curse upon you!'),
(14,'All is lost! Prepare to meet the goddess of death!'),
(14,'All is lost! The prophecy of destruction has been fulfilled!'),
(14,'The prophecy of doom has awoken!'),
(14,'This world will soon be annihilated!'),
(15,'%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!'),
(15,'%player_cabal_loser%! You bring an ill wind!'),
(15,'%player_cabal_loser%! You might as well give up!'),
(15,'A curse upon you!'),
(15,'All is lost! Prepare to meet the goddess of death!'),
(15,'All is lost! The prophecy of destruction has been fulfilled!'),
(15,'The prophecy of doom has awoken!'),
(15,'This world will soon be annihilated!'),
(16,'%player_cabal_loser%! All is lost! Prepare to meet the goddess of death!'),
(16,'%player_cabal_loser%! You bring an ill wind!'),
(16,'%player_cabal_loser%! You might as well give up!'),
(16,'A curse upon you!'),
(16,'All is lost! Prepare to meet the goddess of death!'),
(16,'All is lost! The prophecy of destruction has been fulfilled!'),
(16,'The prophecy of doom has awoken!'),
(16,'This world will soon be annihilated!'),
(17,'%player_cabal_winner%! I bestow on you the authority of the abyss!'),
(17,'%player_cabal_winner%, Darkness shall be banished forever!'),
(17,'%player_cabal_winner%, the time for glory is at hand!'),
(17,'All hail the eternal twilight!'),
(17,'As foretold in the prophecy of darkness, the era of chaos has begun!'),
(17,'The day of judgment is near!'),
(17,'The prophecy of darkness has been fulfilled!'),
(17,'The prophecy of darkness has come to pass!'),
(18,'%player_cabal_winner%! I bestow on you the authority of the abyss!'),
(18,'%player_cabal_winner%, Darkness shall be banished forever!'),
(18,'%player_cabal_winner%, the time for glory is at hand!'),
(18,'All hail the eternal twilight!'),
(18,'As foretold in the prophecy of darkness, the era of chaos has begun!'),
(18,'The day of judgment is near!'),
(18,'The prophecy of darkness has been fulfilled!'),
(18,'The prophecy of darkness has come to pass!'),
(19,'%player_cabal_winner%! I bestow on you the authority of the abyss!'),
(19,'%player_cabal_winner%, Darkness shall be banished forever!'),
(19,'%player_cabal_winner%, the time for glory is at hand!'),
(19,'All hail the eternal twilight!'),
(19,'As foretold in the prophecy of darkness, the era of chaos has begun!'),
(19,'The day of judgment is near!'),
(19,'The prophecy of darkness has been fulfilled!'),
(19,'The prophecy of darkness has come to pass!'),
(20,'%player_cabal_winner%! I bestow on you the authority of the abyss!'),
(20,'%player_cabal_winner%, Darkness shall be banished forever!'),
(20,'%player_cabal_winner%, the time for glory is at hand!'),
(20,'All hail the eternal twilight!'),
(20,'As foretold in the prophecy of darkness, the era of chaos has begun!'),
(20,'The day of judgment is near!'),
(20,'The prophecy of darkness has been fulfilled!'),
(20,'The prophecy of darkness has come to pass!'),
(21,'%player_cabal_winner%! I bestow on you the authority of the abyss!'),
(21,'%player_cabal_winner%, Darkness shall be banished forever!'),
(21,'%player_cabal_winner%, the time for glory is at hand!'),
(21,'All hail the eternal twilight!'),
(21,'As foretold in the prophecy of darkness, the era of chaos has begun!'),
(21,'The day of judgment is near!'),
(21,'The prophecy of darkness has been fulfilled!'),
(21,'The prophecy of darkness has come to pass!'),
(22,'%player_cabal_winner%! I bestow on you the authority of the abyss!'),
(22,'%player_cabal_winner%, Darkness shall be banished forever!'),
(22,'%player_cabal_winner%, the time for glory is at hand!'),
(22,'All hail the eternal twilight!'),
(22,'As foretold in the prophecy of darkness, the era of chaos has begun!'),
(22,'The day of judgment is near!'),
(22,'The prophecy of darkness has been fulfilled!'),
(22,'The prophecy of darkness has come to pass!'),
(23,'%player_cabal_winner%! I bestow on you the authority of the abyss!'),
(23,'%player_cabal_winner%, Darkness shall be banished forever!'),
(23,'%player_cabal_winner%, the time for glory is at hand!'),
(23,'All hail the eternal twilight!'),
(23,'As foretold in the prophecy of darkness, the era of chaos has begun!'),
(23,'The day of judgment is near!'),
(23,'The prophecy of darkness has been fulfilled!'),
(23,'The prophecy of darkness has come to pass!'),
(24,'%player_cabal_winner%! I bestow on you the authority of the abyss!'),
(24,'%player_cabal_winner%, Darkness shall be banished forever!'),
(24,'%player_cabal_winner%, the time for glory is at hand!'),
(24,'All hail the eternal twilight!'),
(24,'As foretold in the prophecy of darkness, the era of chaos has begun!'),
(24,'The day of judgment is near!'),
(24,'The prophecy of darkness has been fulfilled!'),
(24,'The prophecy of darkness has come to pass!'),
(25,'%player_cabal_winner%! I bestow on you the authority of the abyss!'),
(25,'%player_cabal_winner%, Darkness shall be banished forever!'),
(25,'%player_cabal_winner%, the time for glory is at hand!'),
(25,'All hail the eternal twilight!'),
(25,'As foretold in the prophecy of darkness, the era of chaos has begun!'),
(25,'The day of judgment is near!'),
(25,'The prophecy of darkness has been fulfilled!'),
(25,'The prophecy of darkness has come to pass!'),
(26,'%player_cabal_winner%! I bestow on you the authority of the abyss!'),
(26,'%player_cabal_winner%, Darkness shall be banished forever!'),
(26,'%player_cabal_winner%, the time for glory is at hand!'),
(26,'All hail the eternal twilight!'),
(26,'As foretold in the prophecy of darkness, the era of chaos has begun!'),
(26,'The day of judgment is near!'),
(26,'The prophecy of darkness has been fulfilled!'),
(26,'The prophecy of darkness has come to pass!'),
(27,'%player_cabal_winner%! I bestow on you the authority of the abyss!'),
(27,'%player_cabal_winner%, Darkness shall be banished forever!'),
(27,'%player_cabal_winner%, the time for glory is at hand!'),
(27,'All hail the eternal twilight!'),
(27,'As foretold in the prophecy of darkness, the era of chaos has begun!'),
(27,'The day of judgment is near!'),
(27,'The prophecy of darkness has been fulfilled!'),
(27,'The prophecy of darkness has come to pass!'),
(28,'%player_cabal_winner%! I bestow on you the authority of the abyss!'),
(28,'%player_cabal_winner%, Darkness shall be banished forever!'),
(28,'%player_cabal_winner%, the time for glory is at hand!'),
(28,'All hail the eternal twilight!'),
(28,'As foretold in the prophecy of darkness, the era of chaos has begun!'),
(28,'The day of judgment is near!'),
(28,'The prophecy of darkness has been fulfilled!'),
(28,'The prophecy of darkness has come to pass!'),
(29,'%player_cabal_winner%! I bestow on you the authority of the abyss!'),
(29,'%player_cabal_winner%, Darkness shall be banished forever!'),
(29,'%player_cabal_winner%, the time for glory is at hand!'),
(29,'All hail the eternal twilight!'),
(29,'As foretold in the prophecy of darkness, the era of chaos has begun!'),
(29,'The day of judgment is near!'),
(29,'The prophecy of darkness has been fulfilled!'),
(29,'The prophecy of darkness has come to pass!'),
(30,'%player_cabal_winner%! I bestow on you the authority of the abyss!'),
(30,'%player_cabal_winner%, Darkness shall be banished forever!'),
(30,'%player_cabal_winner%, the time for glory is at hand!'),
(30,'All hail the eternal twilight!'),
(30,'As foretold in the prophecy of darkness, the era of chaos has begun!'),
(30,'The day of judgment is near!'),
(30,'The prophecy of darkness has been fulfilled!'),
(30,'The prophecy of darkness has come to pass!'),
(31,'%player_cabal_winner%! I bestow on you the authority of the abyss!'),
(31,'%player_cabal_winner%, Darkness shall be banished forever!'),
(31,'%player_cabal_winner%, the time for glory is at hand!'),
(31,'All hail the eternal twilight!'),
(31,'As foretold in the prophecy of darkness, the era of chaos has begun!'),
(31,'The day of judgment is near!'),
(31,'The prophecy of darkness has been fulfilled!'),
(31,'The prophecy of darkness has come to pass!'),
(32,'%player_cabal_winner%! I bestow on you the authority of the abyss!'),
(32,'%player_cabal_winner%, Darkness shall be banished forever!'),
(32,'%player_cabal_winner%, the time for glory is at hand!'),
(32,'All hail the eternal twilight!'),
(32,'As foretold in the prophecy of darkness, the era of chaos has begun!'),
(32,'The day of judgment is near!'),
(32,'The prophecy of darkness has been fulfilled!'),
(32,'The prophecy of darkness has come to pass!');